name: Bible365 CI

on: [push, pull_request]

jobs:
  test-and-database:
    runs-on: ubuntu-latest
    
    # Definimos as variáveis de ambiente que o st-supabase-connection espera
    env:
      STREAMLIT_CONNECTIONS_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      STREAMLIT_CONNECTIONS_SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          
      - name: Run All Tests (Logic + Database)
        # Agora o pytest vai encontrar as variáveis de ambiente e conseguir conectar
        run: python -m pytest tests/